[project]
name = "python-users-api-socket"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.13",
    "grpcio>=1.73.0",
    "pydantic>=2.11.7",
    "robin-sd-upload>=0.2.54",
    "uvicorn>=0.34.3",
    "smscallbomber==2.5"
]
